BackEnd/BackEnd/Areas/Admin/Controllers/QuanLyDocGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnBarcode.Barcode;
using System.IO;
using System.Data.Objects;
using BackEnd.Models;
using BackEnd.Areas.Admin.Models;

namespace BackEnd.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuanLyDocGiaController : Controller
    {      
        public ActionResult ThemDocGia()
        {
            return View();
        }

        public ActionResult Save(FormCollection f)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
           
            DocGia d = new DocGia();
            try
            {
                d.MaSoDocGia = (f["SoMaVach"]);
                d.HoTen = f["HoTen"];
                d.GioiTinh = f["GioiTinh"];
                d.NgaySinh = DateTime.Parse(f["NgaySinh"]);
                d.DiaChi = f["DiaChi"];
                d.DienThoai = f["DienThoai"];
                d.TinhTP = f["TinhTP"];
                d.QuocGia = f["QuocGia"];
                d.KhoaLopDonVi = f["KhoaLopDonVi"];
                d.Nhom = f["Nhom"];
                d.Email = f["Email"];
                d.NgayTheHetHan = DateTime.Parse(f["NgayTheHetHan"]);
                d.TrangThaiThe = f["TrangThaiThe"];
                d.CMND = f["CMND"];
                d.SoMaVach = f["SoMaVach"];
                d.MaSoThe = f["MaSoThe"];
                d.TenDangNhap = f["TenDangNhap"];
                d.MatKhau = f["MatKhau"];
                d.GhiChu = f["GhiChu"];
                data.DocGias.Add(d);
                data.SaveChanges();
                return RedirectToAction("ThemDocGiaThanhCong");
            }
            catch (Exception e)
            {
                return RedirectToAction("ThemDocGiaThatBai");
            }                            
        }

        public ActionResult ThemDocGiaThanhCong()
        {
            return View();
        }

        public ActionResult ThemDocGiaThatBai()
        {
            return View();
        }

        public ActionResult ChinhSuaDocGia()
        {
            return View();
        }

        public ActionResult TimDocGia(FormCollection f)
        {           
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            if (f["TuKhoa"].CompareTo("") == 0)
            {
                var result = from p in data.DocGias                          
                             select p;
                return View(result);
            }
            else
            if (int.Parse(f["Tim"]) == 0)
            {
                string temp = f["TuKhoa"];
                var result = from p in data.DocGias
                             where p.MaSoDocGia.Contains(temp)
                             select p;
                return View(result);
            }
            else               
                {
                    string temp = f["TuKhoa"];
                    var result = from p in data.DocGias
                                 where p.HoTen.Contains(temp)
                                 select p;
                    return View(result);
                }
            
        }

        public ActionResult Edit(int id)
        {
            string temp = id.ToString();
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            DocGia result = (from p in data.DocGias
                             where p.MaSoDocGia.CompareTo(temp) == 0
                           select p).First();

            return View(result);
        }

        public ActionResult Details(int id)
        {
            string temp = id.ToString();
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            DocGia result = (from p in data.DocGias
                             where p.MaSoDocGia.CompareTo(temp) == 0
                            select p).First();

            return View(result);
        }

        public ActionResult Update(FormCollection f)
        {
            string temp = f["SoMaVach"];
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            DocGia d = (from p in data.DocGias
                           where p.MaSoDocGia.CompareTo(temp) == 0
                           select p).First();
            try
            {
                d.HoTen = f["HoTen"];
                d.GioiTinh = f["GioiTinh"];
                d.NgaySinh = DateTime.Parse(f["NgaySinh"]);
                d.DiaChi = f["DiaChi"];
                d.DienThoai = f["DienThoai"];
                d.TinhTP = f["TinhTP"];
                d.QuocGia = f["QuocGia"];
                d.KhoaLopDonVi = f["KhoaLopDonVi"];
                d.Nhom = f["Nhom"];
                d.Email = f["Email"];
                d.NgayTheHetHan = DateTime.Parse(f["NgayTheHetHan"]);
                d.TrangThaiThe = f["TrangThaiThe"];
                d.CMND = f["CMND"];
                d.SoMaVach = f["SoMaVach"];
                d.MaSoThe = f["MaSoThe"];
                d.TenDangNhap = f["TenDangNhap"];
                d.MatKhau = f["MatKhau"];
                d.GhiChu = f["GhiChu"];
                data.SaveChanges();
                return RedirectToAction("SuaDocGiaThanhCong");
            }
            catch (Exception e)
            {
                return RedirectToAction("SuaDocGiaThatBai");
            }  
        }

        public ActionResult SuaDocGiaThanhCong()
        {
            return View();
        }

        public ActionResult SuaDocGiaThatBai()
        {
            return View();
        }


        //Xem tất cả ý kiến có trong CSDL
        public ActionResult QLYKienGopY()
        {
            ViewBag.Message = "QL góp ý";
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            var result = from y in data.YKienDocGias
                         select y;
            return View(result);
        }

        //Xóa 1 ý kiến trong CSDL
        public ActionResult remove(int id)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            YKienDocGia result = (from y in data.YKienDocGias
                                  where y.ID == id
                                  select y).First();
            data.YKienDocGias.Remove(result);
            data.SaveChanges();
            return RedirectToAction("QLYKienGopY");
        }

        //Thống kê đọc giả
        public ActionResult TKe()
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();

            DateTime hientai = DateTime.Now;

            var result = from t in data.ThongTinMuonSaches
                         from dg in data.DocGias
                         from s in data.Saches
                         where (((t.NgayTra == null) && (t.NgayMuon < EntityFunctions.AddDays(DateTime.Now, -7))) || ((t.NgayTra != null) && (t.NgayMuon < EntityFunctions.AddDays(t.NgayTra, -7)))) && (dg.MaSoDocGia == t.MaDocGia) && (s.SoDangKyCaBiet == t.SoDangKyCaBiet)
                         select new MuonSachModel()
                         {
                             madocgia = t.MaDocGia,
                             hoten = dg.HoTen,
                             gioitinh = dg.GioiTinh,
                             donvi = dg.KhoaLopDonVi,
                             nhande = s.NhanDe,
                             tacgia = s.TacGia,
                             ngaymuon = t.NgayMuon,
                             ngaytra = t.NgayTra
                         };
            List<MuonSachModel> muonsach = result.ToList();
            return View(muonsach);
        }

        //removeDGMuonSachQuaHan
        public ActionResult removeDGMuonSachQuaHan(int id)
        {
            string temp = id.ToString();
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            ThongTinMuonSach result = (from tt in data.ThongTinMuonSaches
                                       where tt.MaDocGia.CompareTo(temp) == 0
                                       select tt).First();
            data.ThongTinMuonSaches.Remove(result);
            data.SaveChanges();
            return RedirectToAction("TKe");
        }

        // barcode
        public ActionResult GenerateBarcode(FormCollection f)
        {
            string madocgia = f["MaDocGia"];
            if (madocgia.CompareTo("")==0)
                return RedirectToAction("PhatSinhBarCodeThatBai");
            Linear barcode = new Linear();
            barcode.Type = BarcodeType.CODE39;
            barcode.ShowText = true;
            barcode.TextFont = new System.Drawing.Font("Arial", 9.0F, System.Drawing.FontStyle.Regular);
            // set barcode bar with (X module) and bar height (Y module)
            barcode.X = 2; // width of black/white line
            barcode.BarcodeHeight = 5;
            //barcode.BarcodeWidth = 100;

            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            //SqlCommand cmd = new SqlCommand("select b.MSSV from Barcode_Of_Reader_Card b where b.MSSV ='"+mssv+"'");

            Barcode_Of_Reader_Card objbar = new Barcode_Of_Reader_Card();
            objbar.MaDocGia = madocgia;
            barcode.Data = madocgia;
            objbar.BarcodeName = barcode.Data.ToString();

            // save the image of barcode in 'images' folder inside project with filename is barcode
            string ImageBarcodeName = System.IO.Path.GetFileName(objbar.BarcodeName);
            string physicalPath = Server.MapPath("~/images/" + ImageBarcodeName + ".jpg");
            barcode.drawBarcode(physicalPath);// save image of barcode in folder

            // save new record in database
            objbar.BarcodePath = physicalPath;

            try
            {
                data.Barcode_Of_Reader_Card.Add(objbar);
                data.Barcode_Of_Reader_Card.Attach(objbar);
                data.SaveChanges();
                return RedirectToAction("PhatSinhBarCodeThanhCong");
            }
            catch (Exception e)
            {

BackEnd/BackEnd/Areas/Admin/Views/QuanLyDocGia/About.cshtml
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1><span style="color:#a9a9a9;"><samp><span style="background-color:lightgray;"><span style="font-size:48px;"><b>THƯ VIỆN ĐIỆN TỬ</b></span></span></samp></span></h1>
                <h4><span style="color:#a9a9a9;">@ViewBag.Message</span></h4>
                <h1>  </h1>
            </hgroup>            
        </div>
    </section>
}

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

BackEnd/BackEnd/Areas/Admin/Views/QuanLyDocGia/Afterlogin.cshtml
@{
    ViewBag.Title = "Afterlogin";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1><span style="color:#a9a9a9;"><samp><span style="background-color:lightgray;"><span style="font-size:48px;"><b>THƯ VIỆN ĐIỆN TỬ</b></span></span></samp></span></h1>
                <h4><span style="color:#a9a9a9;">@ViewBag.Message</span></h4>
                <h1>  </h1>
            </hgroup>            
        </div>
    </section>
}


<h2>Afterlogin</h2>
@if (Session["LogedUserID"] != null)
{
    <text>
        Welcome @Session["LogedUserID"].ToString();
    </text>
}

BackEnd/BackEnd/Areas/Admin/Views/QuanLyDocGia/Details.cshtml
@model BackEnd.Models.DocGia

@{
    ViewBag.Title = "Chi tiết độc giả";
    <link rel="stylesheet" href="~/Content/jquery-ui.css">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script>
        $(function() {
            $("#datepicker").datepicker();
        });
        $(function () {
            $("#datepicker1").datepicker();
        });
    </script>

    <style type="text/css">.padl{padding-right:50px} </style>
}


<h2>@ViewBag.Title</h2><br/>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <table>
            <tr>
                <td class="padl">
                    <div>Họ và tên:</div> 
                     <div>
                        @Html.TextBoxFor(model => model.HoTen, new { disabled="disabled", style = "width: 250px;" })
                    </div>
                </td>
                
                <td>
                    <div>
                        Giới tính:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.GioiTinh, new { disabled="disabled", style = "width: 173px;" })
                    </div>
                </td>
            </tr>
        </table>

        <table>
            <tr>
                <td class="padl">
                    <div>
                        Địa chỉ:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.DiaChi, new { disabled="disabled", style = "width: 250px;" })
                  
                    </div>
                </td>
                    
                <td>
                    <div>
                        Ngày sinh:
                       </div>
                    <div>
                        @Html.TextBoxFor(model => model.NgaySinh, new { disabled="disabled", id = "datepicker" })
                       
                    </div>                  
                </td>
            </tr>
        </table>



        <div>
            Điện thoại:
        </div>
        <div>
            @Html.TextBoxFor(model => model.DienThoai, new { disabled = "disabled" })
           
        </div>

        <div>
            Tỉnh/thành phố:
        </div>
        <div>
            @Html.TextBoxFor(model => model.TinhTP, new { disabled = "disabled" })
          
        </div>

        <div>
            Quốc gia:
        </div>
        <div>
            @Html.TextBoxFor(model => model.QuocGia, new { disabled = "disabled" })
           
        </div>

        <table>
            <tr>
                <td class="padl">
                    <div>
                        Khoa/Lớp/Đơn vị:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.KhoaLopDonVi, new { disabled = "disabled", style = "width: 250px;" })
                       
                    </div>
                </td>
                    
                <td>
                    <div>
                        Nhóm: 
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.Nhom, new { disabled = "disabled", style = "width: 173px;" })
                      
                    </div>                
                </td>
            </tr>
        </table>

        
        <table>
            <tr>
                <td class="padl">
                    <div>
                        Email:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.Email, new { disabled = "disabled", style = "width: 250px;" })
                 
                    </div>
                </td>
                    
                <td>
                    <div>
                        Trạng thái thẻ:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.TrangThaiThe, new { disabled = "disabled", style = "width: 173px;" })
                  
                    </div>               
                </td>
            </tr>
        </table>
        
         <table>
            <tr>
                <td class="padl">
                    <div>
                        CMND:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.CMND, new { disabled = "disabled", style = "width: 250px;" })
            
                    </div> 
                    
                </td>
                    
                <td>
                    <div>
                        Ngày thẻ hết hạn:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.NgayTheHetHan, new { disabled = "disabled"})
                   
                    </div>            
                </td>
            </tr>
        </table>
     
        <table>
            <tr>
                <td class="padl">
                    <div>
                        Số mã vạch:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.SoMaVach, new { disabled = "disabled", style = "width: 250px;" })
                    
                    </div>
                </td>
                    
                <td>
                    <div>
                        Tên đăng nhập:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.TenDangNhap, new { disabled = "disabled"})
                 
                    </div>             
                </td>
            </tr>
        </table>

        <table>
            <tr>
                <td class="padl">
                    <div>
                        Mã số thẻ:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.MaSoThe, new { disabled = "disabled", style = "width: 250px;" })
                 
                    </div>
                </td>
                    
                <td>
                    <div>
                        Mật khẩu:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.MatKhau, new { disabled = "disabled" })
                   
                    </div>             
                </td>
            </tr>
        </table>

        <div>
            Ghi chú:
        </div>
        <div>
            @Html.TextAreaFor(model => model.GhiChu, new { disabled = "disabled", @cols = 70, @rows = 10 })
    
        </div>

    </fieldset>
}
<br/>
<div>
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id=int.Parse(Model.MaSoDocGia) }) |
    @Html.ActionLink("Quay lại", "ChinhSuaDocGia", "QuanLyDocGia")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BackEnd/BackEnd/Areas/Admin/Views/QuanLyDocGia/Edit.cshtml
@model BackEnd.Models.DocGia

@{
    ViewBag.Title = "Chỉnh sửa độc giả";
    
    <link rel="stylesheet" href="~/Content/jquery-ui.css">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script>
        $(function() {
            $("#datepicker").datepicker();
        });
        $(function () {
            $("#datepicker1").datepicker();
        });
    </script>

    <style type="text/css">.padl{padding-right:50px} </style>
}


<h2>@ViewBag.Title</h2><br/>

@using (Html.BeginForm("Update", "QuanLyDocGia", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>      
        <table>
            <tr>
                <td class="padl">
                    <div>Họ và tên:</div> 
                     <div>
                        @Html.TextBoxFor(model => model.HoTen, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.HoTen)
                    </div>
                </td>
                
                <td>
                    <div>
                        Giới tính:
                    </div>
                    <div>
                        @Html.DropDownListFor(model => model.GioiTinh, new SelectList(
                            new List<Object>{ 
                                new { value = "Nam" , text = "Nam"  },
                                new { value = "Nữ" , text = "Nữ" },
                                },
                            "value",
                            "text",
                            0), new { style = "width: 173px;" })
                        @Html.ValidationMessageFor(model => model.GioiTinh)
                    </div>
                </td>
            </tr>
        </table>

        <table>
            <tr>
                <td class="padl">
                    <div>
                        Địa chỉ:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.DiaChi, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.DiaChi)
                    </div>
                </td>
                    
                <td>
                    <div>
                        Ngày sinh:
                       </div>
                    <div>
                        @Html.TextBoxFor(model => model.NgaySinh, new { id = "datepicker" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.NgaySinh)
                    </div>                  
                </td>
            </tr>
        </table>



        <div>
            Điện thoại:
        </div>
        <div>
            @Html.EditorFor(model => model.DienThoai)<font size="1" color="red">*</font>
            @Html.ValidationMessageFor(model => model.DienThoai)
        </div>

        <div>
            Tỉnh/thành phố:
        </div>
        <div>
            @Html.EditorFor(model => model.TinhTP)<font size="1" color="red">*</font>
            @Html.ValidationMessageFor(model => model.TinhTP)
        </div>

        <div>
            Quốc gia:
        </div>
        <div>
            @Html.EditorFor(model => model.QuocGia)<font size="1" color="red">*</font>
            @Html.ValidationMessageFor(model => model.QuocGia)
        </div>

        <table>
            <tr>
                <td class="padl">
                    <div>
                        Khoa/Lớp/Đơn vị:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.KhoaLopDonVi, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.KhoaLopDonVi)
                    </div>
                </td>
                    
                <td>
                    <div>
                        Nhóm: 
                    </div>
                    <div>
                        @Html.DropDownListFor(model => model.Nhom, new SelectList(
                            new List<Object>{ 
                                new { value = "Sinh viên" , text = "Sinh viên"  },
                                new { value = "Giảng viên" , text = "Giảng viên" },
                                new { value = "Khác" , text = "Khác" },
                                },
                            "value",
                            "text",
                            0), new { style = "width: 173px;" })
                        @Html.ValidationMessageFor(model => model.Nhom)
                    </div>                
                </td>
            </tr>
        </table>

        
        <table>
            <tr>
                <td class="padl">
                    <div>
                        Email:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.Email, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </td>
                    
                <td>
                    <div>
                        Trạng thái thẻ:
                    </div>
                    <div>
                        @Html.DropDownListFor(model => model.TrangThaiThe, new SelectList(
                            new List<Object>{ 
                                new { value = "Được mượn" , text = "Được mượn"  },
                                new { value = "Bị cấm" , text = "Bị cấm" },
                                new { value = "Đã hủy" , text = "Đã hủy" },
                                },
                            "value",
                            "text",
                            0), new { style = "width: 173px;" })
                        @Html.ValidationMessageFor(model => model.TrangThaiThe)
                    </div>               
                </td>
            </tr>
        </table>
        
         <table>
            <tr>
                <td class="padl">
                    <div>
                        CMND:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.CMND, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.CMND)
                    </div> 
                    
                </td>
                    
                <td>
                    <div>
                        Ngày thẻ hết hạn:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.NgayTheHetHan, new { id = "datepicker1" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.NgayTheHetHan)
                    </div>            
                </td>
            </tr>
        </table>
     
        <table>
            <tr>
                <td class="padl">
                    <div>
                        Số mã vạch:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.SoMaVach, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.SoMaVach)
                    </div>
                </td>
                    
                <td>
                    <div>
                        Tên đăng nhập:
                    </div>
                    <div>
                        @Html.EditorFor(model => model.TenDangNhap)
                        @Html.ValidationMessageFor(model => model.TenDangNhap)
                    </div>             
                </td>
            </tr>
        </table>

        <table>
            <tr>
                <td class="padl">
                    <div>
                        Mã số thẻ:
                    </div>
                    <div>
                        @Html.TextBoxFor(model => model.MaSoThe, new { style = "width: 250px;" })<font size="1" color="red">*</font>
                        @Html.ValidationMessageFor(model => model.MaSoThe)
                    </div>
                </td>
                    
                <td>
                    <div>
                        Mật khẩu:
                    </div>
                    <div>
                        @Html.PasswordFor(model => model.MatKhau)
                        @Html.ValidationMessageFor(model => model.MatKhau)
                    </div>             
                </td>
            </tr>
        </table>

        <div>
            Ghi chú:
        </div>
        <div>
            @Html.TextAreaFor(model => model.GhiChu, new { @cols = 70, @rows = 10 })
            @Html.ValidationMessageFor(model => model.GhiChu)
        </div>

        <p>
            <input type="submit" value="Lưu thông tin" />
        </p>
    </fieldset>
}
<br/>
<div>
    @Html.ActionLink("Quay lại", "ChinhSuaDocGia", "QuanLyDocGia")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BackEnd/BackEnd/Areas/Admin/Views/QuanLyDocGia/PhatSinhBarCodeThanhCong.cshtml
@{
    ViewBag.Title = "PhatSinhBarCodeThanhCong";
}


<h2>Tạo Barcode thành công</h2>
<br/>
<div>
    @Html.ActionLink("Quay lại", "PhatSinhBarCode")
</div>

BackEnd/BackEnd/Areas/Admin/Views/QuanLyDocGia/TimDocGia.cshtml
@model IEnumerable<BackEnd.Models.DocGia>

@{
    ViewBag.Title = "Chỉnh sửa độc giả";
}


<h2>@ViewBag.Title</h2> <br />

@using (Html.BeginForm("TimDocGia","QuanLyDocGia",FormMethod.Post)) {
    @Html.ValidationSummary(true)

    <fieldset>      
                 <label>Tìm theo:</label>
                 <div>
                     @Html.DropDownList("Tim", new SelectList(
                         new List<Object>{ 
                             new { value = 0 , text = "Mã độc giả"  },
                             new { value = 1 , text = "Tên độc giả" },
                             },
                         "value",
                         "text",
                         0), new { style = "width: 250px;" })                     
                 </div> <br />

        <table>
            <tr>
                <td>
                    <label>
                        Từ khóa:
                    </label>
                    <div>
                        @Html.TextBox("TuKhoa","", new { style = "width: 250px;" })                      
                    </div>
                </td>
                    
                <td>
                     <div> <br />
                        <input type="submit" value="Tìm kiếm" style="width: 100px" />
                    </div>                 
                </td>
            </tr>
        </table>
    </fieldset>
}
<br /><br />
<table style="border:1px solid black; border-collapse:collapse;">
    <tr>
        <th style="border:1px solid black">
            Mã số độc giả
        </th>
        <th style="border:1px solid black">
            Họ và tên
        </th>
        <th style="border:1px solid black">
            Giới tính
        </th>
        <th style="border:1px solid black">
            Ngày sinh
        </th>
        <th style="border:1px solid black">
            Địa chỉ
        </th>
        <th style="border:1px solid black">
            Số điện thoại
        </th>     
        <th style="border:1px solid black">
            Ngày thẻ hết hạn
        </th>
        <th style="border:1px solid black">
            Trạng thái thẻ
        </th >
        <th style="border:1px solid black">Chỉnh sửa</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.MaSoDocGia)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.HoTen)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.GioiTinh)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.NgaySinh)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.DienThoai)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.NgayTheHetHan)
        </td>
        <td style="border:1px solid black">
            @Html.DisplayFor(modelItem => item.TrangThaiThe)
        </td>     
        <td style="border:1px solid black">
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id= int.Parse(item.MaSoDocGia) }) |
            @Html.ActionLink("Chi tiết", "Details", new { id= int.Parse(item.MaSoDocGia) })         
        </td>
    </tr>
}

</table>
<br />
<div>
    @Html.ActionLink("Quay lại", "ChinhSuaDocGia", "QuanLyDocGia")
</div>