BackEnd/BackEnd/Areas/Admin/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BackEnd.Areas.Admin.Models;
using BackEnd.Models;

namespace BackEnd.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PartialController : Controller
    {
        //
        // GET: /Admin/Partial/

        [ChildActionOnly]
        public PartialViewResult GetMenu(string id,string id2)
        {
            QuanLyThuVienEntities db = new QuanLyThuVienEntities();
            ViewBag.data = db.DanhMucAdmins.Where(x => x.parent == null).OrderBy(x=>x.oder).ToList();
            ViewBag.id = id;
            ViewBag.id2 = id2;
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult GetMenu2(string id, string parent)
        {
            QuanLyThuVienEntities db = new QuanLyThuVienEntities();
            ViewBag.data = db.DanhMucAdmins.Where(x => x.parent.Equals(parent)).OrderBy(x => x.oder).ToList();
            ViewBag.id = id;
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult GetMenu22(string id, string parent)
        {
            QuanLyThuVienEntities db = new QuanLyThuVienEntities();
            ViewBag.data = db.DanhMucAdmins.Where(x => x.parent.Equals(parent)).OrderBy(x => x.oder).ToList();
            ViewBag.id = id;
            return PartialView();
        }

        //[ChildActionOnly]
        //public PartialViewResult GetDanhMucDrop(string value,int type,string danhmuccon)
        //{
        //    EAuctionEntities db = new EAuctionEntities();
        //    var data = db.DanhMucs.Where(x=>x.parent == null && x.type == type).ToList();
        //    ListItemlModel model = new ListItemlModel();
        //    model.value = value;
        //    model.listitem = new SelectList(data, "id", "name");
        //    ViewBag.type = type;
        //    ViewBag.id = value;
        //    ViewBag.danhmuccon = danhmuccon;
        //    return PartialView(model);
        //}

        //[ChildActionOnly]
        //public PartialViewResult GetDanhMucDropdf(string id, int type, string danhmuccon)
        //{
        //    ThietBiYTeEntities db = new ThietBiYTeEntities();
        //    var data = db.DanhMucs.Where(x => x.parent.Equals(id) && x.type == 1).ToList();
        //    ListItemlModel model = new ListItemlModel();
        //    model.listitem = new SelectList(data, "id", "name");
        //    model.danhmuccon = danhmuccon;
        //    return PartialView("GetDanhMucDrop2", model);
        //}

        //[HttpPost]
        //public PartialViewResult GetDanhMucDrop2(string id,int type,string danhmuccon)
        //{
        //    ThietBiYTeEntities db = new ThietBiYTeEntities();
        //    var data = db.DanhMucs.Where(x => x.parent.Equals(id) && x.type == 1).ToList();
        //    ListItemlModel model = new ListItemlModel();
        //    model.listitem = new SelectList(data, "id", "name");
        //    model.danhmuccon = danhmuccon;
        //    return PartialView(model);
        //}
    }
}

BackEnd/BackEnd/Areas/Admin/Views/Partial/GetDanhMucDrop.cshtml
@{
    List<BackEnd.DanhMuc> data = ViewBag.data as List<BackEnd.DanhMuc>;    
}
@model BackEnd.Areas.Admin.Models.ListItemlModel
<div class="formRow">
    <div class="grid3">
        <label>
            Chọn Danh Mục Gốc :</label></div>
    <div class="grid9 noSearch">
        @Html.DropDownListFor(x => x.value, Model.listitem,"Hãy Chọn Một Danh Mục",new { @class = "select" })
    </div>
    <div class="clear">
    </div>
</div>
<div id="loaddrop">
    @Html.Action("GetDanhMucDropdf", "Partial", new { id = ViewBag.id,type = 1,danhmuccon =ViewBag.danhmuccon})
</div>
<script language="javascript">
    $("#value").change(function () {
        var value = $("#value").val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetDanhMucDrop2","Partial")',
            data: { id: value,type:@ViewBag.type }, // serializes the form's elements.
            success: function (data) {
                $("#loaddrop").html(data); // show response from the php script.
            }
        });
    });
</script>

BackEnd/BackEnd/Areas/Admin/Views/Partial/GetDanhMucDrop2.cshtml
@model BackEnd.Areas.Admin.Models.ListItemlModel
@if (Model.listitem.Count() > 0)
{
    <div class="formRow">
        <div class="grid3">
            <label>
                Chọn Danh Mục Con :</label></div>
        <div class="grid9 noSearch">
            @Html.DropDownListFor(x=>x.danhmuccon, Model.listitem, new { @class = "select" })
        </div>
        <div class="clear">
        </div>
    </div>
}

BackEnd/BackEnd/Areas/Admin/Views/Partial/GetMenu.cshtml
@{
    List<BackEnd.Models.DanhMucAdmin> data = ViewBag.data as List<BackEnd.Models.DanhMucAdmin>;    
}

@for (int i = 0; i < data.Count; i++)
{
    if (data[i].id.Equals(ViewBag.id))
    {
        <li><a href="@data[i].link" title="" class="active"><img src="~/@data[i].icon" alt="" /><span>@data[i].name</span></a>
            @Html.Action("GetMenu2", "Partial", new { id = ViewBag.id2, parent = data[i].id })
        </li>
    }
    else
    {
        <li><a href="@data[i].link" title=""><img src="~/@data[i].icon" alt="" /><span>@data[i].name</span></a>
            @Html.Action("GetMenu2", "Partial", new { id = ViewBag.id2, parent = data[i].id })
        </li>
    }
}

BackEnd/BackEnd/Areas/Admin/Views/Partial/GetMenu2.cshtml
@{
    List<BackEnd.Models.DanhMucAdmin> data = ViewBag.data as List<BackEnd.Models.DanhMucAdmin>;    
}
@if (data.Count > 0)
{
    <ul>
        @for (int i = 0; i < data.Count; i++)
        {
            if (data[i].id.Equals(ViewBag.id))
            {
            <li class="activeli">
            <a href="@data[i].link" title="" class="this">
                <span class="@data[i].icon"></span>@data[i].name</a></li>
            }
            else
            {
            <li>
            <a href="@data[i].link" title="">
                <span class="@data[i].icon"></span>@data[i].name</a></li>
            }
        }
    </ul>
}

BackEnd/BackEnd/Areas/Admin/Views/Partial/GetMenu22.cshtml
@{
    List<BackEnd.Models.DanhMucAdmin> data = ViewBag.data as List<BackEnd.Models.DanhMucAdmin>;    
}
@if (data.Count > 0)
{
    <ul class="subNav">
        @for (int i = 0; i < data.Count; i++)
        {
            if (data[i].id.Equals(ViewBag.id))
            {
            <li class="activeli">
            <a href="@data[i].link" title="" class="this">
                <span class="@data[i].icon"></span>@data[i].name</a></li>
            }
            else
            {
            <li>
            <a href="@data[i].link" title="">
                <span class="@data[i].icon"></span>@data[i].name</a></li>
            }
        }
    </ul>
}